modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/TeamFelnull/IWasi/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "iwasi"
version = "${version}"
displayName = "IWasi"
authors = "MORIMORI0317, Alfort121R"
credits = "FelNull developers"
description = '''
The Ikisugi MOD...
'''
#logoFile = ""

[[dependencies.iwasi]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwasi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwasi]]
modId = "architectury"
mandatory = true
versionRange = "[4.1.32,)"
ordering = "AFTER"
side = "BOTH"